USE POC_DB;

CREATE TABLE POC_CLIENTES (
CODIGO INT IDENTITY(1,1) NOT NULL UNIQUE,
NOME VARCHAR(60) NOT NULL,
EMAIL VARCHAR(100),
CONTATO VARCHAR(11) NOT NULL UNIQUE,
CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO)
);

CREATE TABLE POC_PRODUTOS (
CODIGO INT IDENTITY(1,1) NOT NULL,
DESCRICAO VARCHAR(30) NOT NULL UNIQUE,
VALOR DECIMAL(18, 2) NOT NULL,
QUANTIDADE INT NOT NULL,
CONSTRAINT PK_PEDIDO PRIMARY KEY (CODIGO),
CONSTRAINT PROD_VAL_POSITIVO CHECK (VALOR > 0),
CONSTRAINT PROD_QTD_POSITIVO CHECK (QUANTIDADE >= 0)
);

CREATE TABLE POC_PEDIDOS (
CODIGO INT IDENTITY(1,1) NOT NULL,
CODIGO_CLIENTE INT NOT NULL,
NOME_CLIENTE VARCHAR(60) NOT NULL,
VALOR_PEDIDO DECIMAL (18, 2) NOT NULL,
DATA_PEDIDO VARCHAR(20) NOT NULL,
ENVIAR_POR_EMAIL BIT NOT NULL DEFAULT 0,
CONSTRAINT FK_CLIENTE FOREIGN KEY (CODIGO_CLIENTE)
REFERENCES POC_CLIENTES (CODIGO),
CONSTRAINT PK_PEDIDOS PRIMARY KEY (CODIGO),
CONSTRAINT PED_VALOR_POSITIVO CHECK (VALOR_PEDIDO >= 0)
);

CREATE TABLE POC_PRODUTOS_PEDIDO (
CODIGO INT IDENTITY(1, 1) NOT NULL,
CODIGO_PEDIDO INT NOT NULL,
CODIGO_PRODUTO INT NOT NULL,
QUANTIDADE INT NOT NULL,
CONSTRAINT PRODPED_QTD_POSITIVO CHECK (QUANTIDADE > 0),
CONSTRAINT FK_PEDIDO FOREIGN KEY (CODIGO_PEDIDO)
REFERENCES POC_PEDIDOS (CODIGO)
ON DELETE CASCADE,
CONSTRAINT FK_PRODUTOS FOREIGN KEY (CODIGO_PRODUTO)
REFERENCES POC_PRODUTOS (CODIGO)
ON DELETE CASCADE
);